name: umi-amplicon
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  # Preprocessing
  - fastp
  
  # Core UMI tools
  - umi_tools
  
  # Quality control
  - fastqc
  - multiqc
  
  # Alignment (optional)
  - bwa
  - samtools
  
  # Python dependencies  
  - python>=3.9
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - plotly>=5.0
  # Note: kaleido removed - not available on macOS, HTML reports don't need it

